### PR TITLE
Bundled chez

### PR DESCRIPTION
**Pull request by ghost**
This pull request modifies the Makefile to include an uninstall option: build and build-stable scripts are linux only tho and some stuff is hardcoded (like the arch for chezscheme inside the build.sh script)

### CODE REVIEW

**Comment by gwatt** [comment]
Thanks for putting this together. However, I don't want to add a submodule on ChezScheme, nor do I want to add multiple extra build scripts. I would prefer to streamline the current build process of gen-config + make, if possible.
The uninstall target is a good idea. I'm not sure where that leaves this PR though

**Comment by ghost** [comment]
Maybe it's better to rely on the already existing installation of ChezScheme and drop the github submodule for more stability then

**Comment by ghost** [comment]
Git submodule has been removed permanently from the build process: now the shell script relies on the installed **stable** version of chezscheme.

**Comment by ghost** [comment]
"Stream lined" the process by simply adding a `(system "make")` at the end of the gen-config.ss script. Now the bash script is not needed anymore thus making this cross platform :smile:

**Pull request merged**
