### PR TITLE
Provide logical program name, not temp file

### LINKED ISSUE #6: (car (command-line)) is a random /tmp file
Compile this program with chez-exe:

```scheme
(import (rnrs))
(write (command-line))
(newline)
```

When run it will print something like `("/tmp/schemeprogramPnhgz8")` instead of e.g. `("foo.ss")`.

I don't see any obvious way to fix it without patching Chez.

### PR DESCRIPTION
**Pull request by gwatt**
@weinholt This should fix #6 It currently works for linux, but I still need to test this on windows and mac os x.

### CODE REVIEW

**Comment by weinholt** [comment]
Tested and works on Linux. Cool!

**Comment by weinholt** [comment]
Btw, does the new custom boot image give you a place where you can unlink one or both of the files in /tmp?

**Comment by gwatt** [comment]
Program exit should be cleaning up those temp files.

**Comment by weinholt** [comment]
Just seems cleaner to unlink them as soon as nothing needs to open them. It's no big deal, I guess.

**Pull request merged**
